
Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: C:/Workspace/assets/OCR/paddle_ocr/output/rec_korean_finetune
  save_epoch_step: 20
  eval_batch_step: [0, 200]
  cal_metric_during_train: true
  pretrained_model: C:/Workspace/assets/OCR/paddle_ocr/pretrain_models/korean_PP-OCRv3_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: 
  character_dict_path: PaddleOCR/ppocr/utils/dict/korean_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  save_res_path: C:/Workspace/assets/OCR/paddle_ocr/output/rec_korean_finetune/predicts_korean.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: True
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Workspace/assets/OCR/paddle_ocr/train_data/crop_img
    label_file_list:
    - C:/Workspace/assets/OCR/paddle_ocr/train_data/crop_img/rec_gt.txt
    transforms:
    - DecodeImage: 
        img_mode: BGR
        channel_first: false
    - RecAug:
    - CTCLabelEncode: 
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: true
    batch_size_per_card: 16
    drop_last: true
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Workspace/assets/OCR/paddle_ocr/train_data/crop_img
    label_file_list:
    - C:/Workspace/assets/OCR/paddle_ocr/train_data/crop_img/rec_gt.txt
    transforms:
    - DecodeImage: 
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: 
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 16
    num_workers: 0
